name: project_name
description: Project description
homepage: https://example.com

publish_to: 'none'

version: 1.0.0+69

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:

dev_dependencies:

flutter:
  uses-material-design: true